.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "MAKE" "1" "August 2014" "" ""
.
.SH "NAME"
\fBmake\fR \-\- run make for all local dependencies
.
.SH "SYNOPSIS"
.
.nf
bdo make [target], [target]
.
.fi
.
.SH "DESCRIPTION"
.
.nf
It finds local dependencies that are symlinked and iteratively runs
`make` for each of them\. This means your working directory should be
the root of your project where a correctly populated `node_modules`
directory should exist\.
.
.fi
.
.SH "EXAMPLE"
.
.nf
    $ cd bdo\-labs/backstage
    $ npm install
    $ bdo link
    $ bdo make
.
.fi
.
.SH "SEE ALSO"
.
.nf
    bdo\-link(1)
.
.fi
